version: "3"
services :
  factory_locator_subsystem:
    image: 1eedwlwaw435eeed23/factlocsub
    deploy: 
      replicas: 10
      placement:
        constraints: [node.role == manager]
    container_name: fact_loc
    ports:
      - "3232:8080"
    restart: always
    